services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-tg-bot-app
    restart: always
    environment:
      # Database
      DATABASE_URL: postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-password}@postgres:5432/${DATABASE_NAME:-nest_tg_bot}

      # Telegram Bot
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_IDS: ${ADMIN_IDS}

      # WireGuard API
      WIREGUARD_API: ${WIREGUARD_API}
      WIREGUARD_PASSWORD: ${WIREGUARD_PASSWORD}

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_password}

      # App Settings
      NODE_ENV: production
      PORT: 3000
      TRIAL_PERIOD_DAYS: ${TRIAL_PERIOD_DAYS:-7}

      # Payments (если используется)
      PAYMENT_PROVIDER_TOKEN: ${PAYMENT_PROVIDER_TOKEN}

      # Timezone
      TZ: Europe/Moscow
    ports:
      - '${APP_PORT:-3000}:3000'
    networks:
      - bot-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  
networks:
  bot-network:
    driver: bridge
